# Generated by Django 2.2.5 on 2019-09-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address1', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('city', models.CharField(max_length=256)),
                ('state_province', models.CharField(default='', max_length=256)),
                ('post_code', models.CharField(default='', max_length=256)),
                ('country_code', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Customer')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Address')),
                ('warehouse_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sku', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
        ),
    ]
